name: tests ci
# This workflow runs the pipeline with the minimal test dataset to check that it completes any errors
on:
  push:
    branches: [develop]
  workflow_run:
    workflows: ["deploy dev"]
    branches: [develop]
    types: [completed]
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Run tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Run pipeline with test data
        run: |
          docker run --privileged buisciii/plasmidid:dev bash test/test.sh
